<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Framework.BuildingBlock</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="MediatR" />
        <PackageReference Include="Volo.Abp.LuckyPenny.AutoMapper" />
        <PackageReference Include="Volo.Abp.Ddd.Application" />
        <ProjectReference Include="..\Framework.BuildingBlock.Application.Contracts\Framework.BuildingBlock.Application.Contracts.csproj" />
        <ProjectReference Include="..\Framework.BuildingBlock.Domain\Framework.BuildingBlock.Domain.csproj" />
    </ItemGroup>
</Project>